server:
  port: 8082
  servlet:
    path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: root
  application:
    name: user-service
mybatis:
  type-aliases-package: com.andy.user.pojo

#控制日志的级别 key：value（包名：日志级别）
logging:
  level:
    com.andy: debug
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka #,http://127.0.0.1:10087/eureka
  instance:
    prefer-ip-address: true
#    hostname: andy.lian.comI
    ip-address: 127.0.0.1
#    随机负载均衡配置
user-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
